AzureSignTool/AuthenticodeKeyVaultSigner.cs
AzureSignTool/Interop/mssign32.cs
AzureSignTool/KeyVaultConfigurationDiscoverer.cs
AzureSignTool/Logger.cs
AzureSignTool/Program.cs
AzureSignTool/StructureManager.cs

Error handling

---

AzureSignTool/AuthenticodeKeyVaultSigner.cs
AzureSignTool/ErrorOr.cs
AzureSignTool/Program.cs
README.md

This allows specifying additional certificates for path building.
Fixes #9.

Additional certs for chain building.

---

AzureSignTool/AuthenticodeKeyVaultSigner.cs
AzureSignTool/HRESULT.cs
AzureSignTool/KeyVaultSigningContext.cs
AzureSignTool/Program.cs
AzureSignTool/SipExtensionFactory.cs
README.md

Page hashing

---

AzureSignTool/AuthenticodeKeyVaultSigner.cs
AzureSignTool/KeyVaultSigningContext.cs
AzureSignTool/Logger.cs
AzureSignTool/Program.cs

Pass around a logging object so we can correlate events better.

Logging correlation

---

.vsts-ci.yml
CodeCoverage.runsettings
Directory.Build.props
src/AzureSign.Core/AzureSign.Core.csproj
src/AzureSignTool/AzureSignTool.csproj
test/AzureSign.Core.Tests/AzureSign.Core.Tests.csproj
version.json

Adds auto-versioning and code coverage

Versioning

---

README.md

Add a badge!

---

AzureSignTool.sln
README.md
src/AzureSign.Core/AlgorithmTranslator.cs
src/AzureSignTool/AzureSignTool.csproj
test/AzureSign.Core.Tests/AlgorithmTranslatorTests.cs
test/AzureSign.Core.Tests/AuthenticodeKeyVaultSignerTests.cs

Support SHA1 signing.

---

src/AzureSignTool/SignCommand.cs

If we don't dispose the logger factory it seems that some log
messages don't get written to the console.

Dispose logger factory.

---

Directory.Build.props
Directory.Build.targets
src/AzureSignTool/AccessTokenCredential.cs
src/AzureSignTool/AzureKeyVaultMaterializedConfiguration.cs
src/AzureSignTool/AzureKeyVaultSignConfigurationSet.cs
src/AzureSignTool/AzureSignTool.csproj
src/AzureSignTool/KeyVaultConfigurationDiscoverer.cs
src/AzureSignTool/SignCommand.cs
test/AzureSign.Core.Tests/AzureSign.Core.Tests.csproj

This PR does a few things:
1. Adds deterministic build settings
2. Updates to latest Key Vault SDK
3. By way of 2, adds support for Managed Identities

Use latest Azure SDK

---

README.md
WALKTHROUGH.md

A follow-up from #84. 
Comments / edits welcome.

Add walk-through doc and link

---

.vscode/launch.json
.vscode/tasks.json
src/AzureSignTool/SignCommand.cs

* The VSCode files were not pointing to correct paths.
* The validation errors did not contain the right argument names.

Misc. cleanup.

---

src/AzureSignTool/KeyVaultConfigurationDiscoverer.cs

Seems like it would help when diagnosing #84.
I did this quickly; happy to clean it up based on feedback, or feel free to close if it's not helpful.

Add additional logging when KeyVaultError occurs

---

AzureSignTool.sln
src/AzureSignTool/Program.cs
test/AzureSignTool.Tests/AzureSignTool.Tests.csproj
test/AzureSignTool.Tests/HelpTests.cs

Basic test structure, ensure CLI outputs help text.

Add tests for CLI.

---

Directory.Build.props
src/AzureSignTool/SignCommand.cs

Timestamp warn

---

WALKTHROUGH.md

REDACTED_APPLICATION_CLIENT_SECRET was missing the ending ']'

adding missing ']' to walkthrough

---

README.md
src/AzureSignTool/SignCommand.cs

Added an option to skip files that have already been signed.

Support for skipping already signed files.

---

.github/workflows/pr.yml
src/AzureSign.Core/AuthenticodeKeyVaultSigner.cs
src/AzureSign.Core/AzureSign.Core.csproj
src/AzureSign.Core/MemoryCertificateStore.cs
src/AzureSign.Core/TimeStampConfiguration.cs
src/AzureSignTool/AzureSignTool.csproj
src/AzureSignTool/SignCommand.cs
src/AzureSignTool/runtimeconfig.template.json
test/AzureSign.Core.Tests/AzureSign.Core.Tests.csproj
test/AzureSignTool.Tests/AzureSignTool.Tests.csproj

Other small things:
* Enable nullability on the Core project.
* Update dependencies.

Update to .NET 6.

---

.github/workflows/pr.yml
Directory.Build.props
src/AzureSign.Core/AlgorithmTranslator.cs
src/AzureSign.Core/AuthenticodeKeyVaultSigner.cs
src/AzureSign.Core/AzureSign.Core.csproj
src/AzureSign.Core/Interop/crypt32.cs
src/AzureSignTool/AccessTokenCredential.cs
src/AzureSignTool/AzureKeyVaultMaterializedConfiguration.cs
src/AzureSignTool/AzureKeyVaultSignConfigurationSet.cs
src/AzureSignTool/AzureSignTool.csproj
src/AzureSignTool/SignCommand.cs
test/AzureSign.Core.Tests/AzureSign.Core.Tests.csproj
test/AzureSignTool.Tests/AzureSignTool.Tests.csproj

* Bump to .NET 8
* Update dependencies and actions
* Minor syntax cleanup for new language features

Update to .NET 8

---

src/AzureSignTool/Program.cs
test/AzureSign.Core.Tests/AuthenticodeKeyVaultSignerTests.cs

Support Windows Server 2022 for --append-signature flag

---

README.md

WinGet can now install AzureSignTool.

Add note about WinGet
