AzureSignTool/Program.cs

The subject in the APPX must match the signing certificate. This prints a helpful error message if that appears to be the case.
I'm not real in to the idea of trying to figure out what the expected Subject should be. Unzipping a file and reading an XML file is considerable for this.
Fixes #5.

Better APPX error message.

---

AzureSignTool/AuthenticodeKeyVaultSigner.cs
AzureSignTool/SipExtensionFactory.cs

According to MSDN, `IUknown::Release` should be called on this if it is not null.

Fix COM releasing.

---

AzureSignTool.Tests/AzureSignTool.Tests.csproj
AzureSignTool/AzureSignTool.csproj
AzureSignTool/HRESULT.cs
AzureSignTool/Program.cs

* Convert target framework to netcoreapp2.1
* Add packaging details
* Return E_PLATFORMNOTSUPPORTED if the tool is run on Linux/macOS
I see you already started similar work. Here's how I would have done it.

Update project to build as a .NET Core 2.1 console tool package 

---

src/AzureSignTool/runtimeconfig.template.json

This adds the roll forward policy so the `netcoreapp2.1` tool will run on .NET Core 3 if 2.1 isn't available.

Add roll forward for .NET Core 3

---

src/AzureSignTool/KeyVaultConfigurationDiscoverer.cs

Reverts vcsjones/AzureSignTool#85
This broke the build (need to see why CI didn't catch this), looks like the SDK change moved some things around.
cc @SeanKilleen

Revert "Add additional logging when KeyVaultError occurs"

---

src/AzureSignTool/AzureSignTool.csproj
src/AzureSignTool/Program.cs

If no arguments are specified, show help.
Fix #74

Show help by default.

---

src/AzureSignTool/AzureSignTool.csproj
src/AzureSignTool/SignCommand.cs

The colors seem to sometimes "leak" past the execution of the program.
This might have been fixed by the update to the Extensions.Console
logger, but since it didn't provide a lot of value anyway, disable
them by default, however people can turn them back on anyway.
Off by default makes the most sense since I expect this tool is mostly
used from some kind of automated process.
Fix #73.

Disable colors by default.

---

src/AzureSignTool/SignCommand.cs

When specifying --azure-key-vault-managed-identity the parameter validation failed - and it was later ignored when setting up credentials for the key vault.

Fix managed identity options

---

src/AzureSignTool/KeyVaultConfigurationDiscoverer.cs

Include the error message from the exception when retrieving the certificate fails.
The full stack trace included in the log at trace level - might be too much? If it is, we should at least make sure there is another way to get any inner exception messages at verbose level.
resolves #102

More details in retrieve cert error message.

---

src/AzureSignTool/SignCommand.cs

Enable logging of scopes to the console.
The path of the file being signed is included as a logging scope but is currently not being written to the console because IncludeScopes is false.
**Before:**
```
info: AzureSignTool.SignCommand[0]
Signing file.
info: AzureSignTool.SignCommand[0]
Signing completed successfully.
info: AzureSignTool.SignCommand[0]
Successful operations: 1
info: AzureSignTool.SignCommand[0]
Failed operations: 0
```
**After:**
```
info: AzureSignTool.SignCommand[0]
=> File: D:\signtest\test.exe
Signing file.
info: AzureSignTool.SignCommand[0]
=> File: D:\signtest\test.exe
Signing completed successfully.
info: AzureSignTool.SignCommand[0]
Successful operations: 1
info: AzureSignTool.SignCommand[0]
Failed operations: 0
```

Log path of file being signed to the console.

---

src/AzureSign.Core/AuthenticodeKeyVaultSigner.cs
src/AzureSignTool/SignCommand.cs
test/AzureSign.Core.Tests/AuthenticodeKeyVaultSignerTests.cs

Expose the existing Win API option to add a signature instead of overriding through the new optional command line argument: **-as** or **--append-signature**

Add support for append signature + tests

---

src/AzureSignTool/KeyVaultConfigurationDiscoverer.cs

If the certificate in Azure Key Vault has no backing key, the KeyId will be null. Give a friendly error message instead of a null-ref.
Fix #207

Properly handle Azure certificates that do not have a key ID

---

src/AzureSignTool/AuthorityHostNames.cs
src/AzureSignTool/AzureKeyVaultSignConfigurationSet.cs
src/AzureSignTool/KeyVaultConfigurationDiscoverer.cs
src/AzureSignTool/SignCommand.cs

This adds an optional CLI argument, `-au` or `--azure-authority` that allows specifying other Azure clouds, like Gov, Germany, etc.
If not specified, the existing behavior will remain, including the `AZURE_AUTHORITY_HOST` environment variable will continue to work.
Closes #161
Closes #158

Add support for other Azure clouds in CLI

---

src/AzureSignTool/Program.cs
test/AzureSignTool.Tests/HelpTests.cs

This adds the version in two places.
1. Just running AzureSignTool with zero options will show the version, in addition to the command help.
2. Introduces a new `--version` output that prints the semver version of AzureSignTool without the help. This may be useful for other tooling that want to parse AzureSignTool's version.
Fix #171

Add --version

---

src/AzureSign.Core/AuthenticodeKeyVaultSigner.cs

Upstream consumers can actually make this work in Windows 10 by shimming the SIPs. Since we don't know if that is happening or not, disable the version check in the library.

Remove Win11 version check

---

src/AzureSignTool/SignCommand.cs

This is a copy/paste error.
The commit fixes a validation error in the `SignCommand.cs` file. The code now correctly checks for the use of '--quiet' and '--verbose' options together, returning an appropriate validation result.

Fix validation error in SignCommand.cs

---

src/AzureSignTool/AzureSignTool.csproj
src/AzureSignTool/Program.cs

If an input on the CLI or in the input-file-list contains a wildcard character, treat it as a glob. For example, this will now work:
```shell
azuresigntool ... C:\files\*.exe # glob by extension
azuresigntool ... C:\files\**\*.exe # glob including subdirectories
```
This implementation explicitly requires the use of an asterisk for globbing. "C:\files\" will not be treated as as sign everything in that directory. It must have a pattern like "C:\files\**\*" to sign everything under a directory.
Fixes #206

File system globbing support

---

src/AzureSignTool/Program.cs

This sets the MaxDegreeOfParallelism to have a default value of "4", instead of the system default. Anything larger than 4 is almost always going to trigger throttling. While this does not alleviate the need for a real rate limit and retrying mechanism, it will reduce the amount of throttling and retrying when it is eventually included.

Set a default MDOP

---

src/AzureSignTool/AzureSignTool.csproj
src/AzureSignTool/Program.cs

This removes the dependency on RSAKeyVaultProvider and uses the functionality provided in the Azure SDK out of the box.
Using the Azure SDK directly lets us specify a retry policy with `CryptographyClientOptions`.

Use Azure SDK for RSA algorithm

---

src/AzureSign.Core/AzureSign.Core.csproj
src/AzureSignTool/AzureSignTool.csproj

Keeping 32-bit support in place is crucial, while at the same time enable new 64-bit related features.
1. Re-enable 32bit Windows publishing needed for signing Office macros (OfficeSIPs needed for signing VBA in office files are only available as 32bit). 
1. PublishAOT still available for 64-bit Windows publishing via build-condition.
This helps fixing problems as described in #126

Re-enable 32bit publishing for office VBA

---

src/AzureSignTool/Program.cs

fixes #257
This code was adding the AzureSignTool Command.Description to the signed file. Sending null allows the codesigning to reuse the existing description.

Add the correct description

---

src/AzureSignTool/AzureKeyVaultSignConfigurationSet.cs
src/AzureSignTool/KeyVaultConfigurationDiscoverer.cs
src/AzureSignTool/Program.cs

This PR adds support for optional AKV certificate version selection.  The parameter has been tested when not present, present but empty string, present with a real value, and present with a bad value.

Adding support for optional Azure Key Vault certificate version selection

---

WALKTHROUGH.md

Add a walkthrough for GitLab CI, with client authentication as well as modern federation token authentication. Inspired by #286 .

doc: add walktrough for GitLab

---

README.md

The DefaultAzureCredential Class is powerful. It tries different authentication methods and allow also the use of existing authentications like in an Azure CLI. See #286 for an example of using modern authentication via JWT-Tokens with the DefaultAzureCredential Class.

doc: add more context about DefaultAzureCredential Class

---

src/AzureSignTool/Program.cs

If AzureSignTool is run on a version of Windows older than 10, it will fail saying `SignerSignEx3` can't be found. This gives a friendlier error message.
Closes #294

Add OS version check

---

WALKTHROUGH.md

It seems like a bad idea to specify more permissions than are actually needed. I was able to get this working with just the following permissions.
It would also be a good idea to include the RBAC permissions here but I have not tested this yet.

Update WALKTHROUGH to specify only the permissions that are actually required
